const personalLoanFormFields = {
  header: "Personel Loan",
  loginFields: [
    {
      title: "Apply For LOan",
      name: "country",
      label: "country",
      type: "select",
      defaultValue: "+91",
      options: [
        { label: "United States (+1)", value: "+1" },
        { label: "United Kingdom (+44)", value: "+44" },
        { label: "Canada (+1)", value: "+1" },
        { label: "Australia (+61)", value: "+61" },
        { label: "Germany (+49)", value: "+49" },
        { label: "France (+33)", value: "+33" },
        { label: "Japan (+81)", value: "+81" },
        { label: "India (+91)", value: "+91" },
      ],
      style: {
        borderRadius: "10px",
        padding: "12px",
      },
      inputOptionClassName: "",
      FeildClassName: "phone-number-input",
      required: true,
    },
    {
      title: "Phone Number",
      name: "phoneNo",
      label: "Phone Number",
      type: "text",
      style: {
        width: "100%",
        border: "none",
        borderBottom: "1px solid black",
        outline: "none",
        padding: "8px",
        boxSizing: "border-box",

        backgroundRepeat: "no-repeat",
        backgroundPosition: "right 8px top 50%",
        backgroundSize: "24px 24px",
      },
      FeildClassName: "phone-number-input",
      inputOptionClassName: "",
      required: true,
    },
  ],
  personalInformationFields: [
    {
      title: "Name",
      name: "name",
      label: "Name",
      type: "text",
      style: {},
      inputOptionClassName: "",
      required: true,
    },
    {
      title: "Email",
      name: "email",
      label: "Email",
      type: "email",
      style: {},
      inputOptionClassName: "",
      required: true,
    },
    {
      title: "Address",
      name: "address",
      label: "Address",
      type: "text",
      style: {},
      inputOptionClassName: "",
      required: true,
    },
  ],

  employmentFields: [
    {
      name: "employment_type",
      title: "Employment Type",
      label: "Employment Type",
      type: "radio",
      options: [
        { label: "Salaried", value: "salaried" },
        { label: "Self Employed Business", value: "self_employed_business" },
        {
          label: "Self Employed Professional",
          value: "self_employed_professional",
        },
      ],
      style: {},
      inputOptionClassName: "",
      required: true,
    },
  ],
  yearlyIncomeField: [
    {
      name: "yearly_income",
      title: "Yearly Income",
      label: "Yearly Income",
      type: "radio",
      options: [
        { label: "Up to ₹ 3 Lacs", value: "up_to_3_lacs" },
        { label: "₹ 3 Lacs - ₹ 4 Lacs", value: "3_4_lacs" },
        { label: "₹ 4 Lacs - ₹ 5 Lacs", value: "4_5_lacs" },
        { label: "₹ 5 Lacs - ₹ 10 Lacs", value: "5_10_lacs" },
        { label: "Above ₹ 10 Lacs", value: "above_10_lacs" },
      ],
      style: {},
      inputOptionClassName: "",
      required: true,
    },
  ],
  primaryBankAccountFields: [
    {
      name: "primary_bank_account",
      title: "Primary Bank Account",
      label: "Primary Bank Account",
      type: "radio",
      options: [
        { label: "State Bank of India", value: "state_bank_of_india" },
        { label: "ICICI Bank", value: "icici_bank" },
        { label: "HDFC Bank", value: "hdfc_bank" },
        { label: "Kotak Mahindra", value: "kotak_mahindra" },
        { label: "Axis Bank", value: "axis_bank" },
        { label: "Citibank", value: "citibank" },
        { label: "Bank of Baroda", value: "bank_of_baroda" },
        { label: "Standard Chartered", value: "standard_chartered" },
        { label: "Central Bank of India", value: "central_bank_of_india" },
        { label: "Federal Bank Limited", value: "federal_bank_limited" },
        { label: "IDFC FIRST Bank Limited", value: "idfc_first_bank_limited" },
        { label: "IDBI Bank Limited", value: "idbi_bank_limited" },
        { label: "YES Bank", value: "yes_bank" },
        { label: "IndusInd Bank Limited", value: "indusind_bank_limited" },
      ],
      style: {},
      inputOptionClassName: "",
      required: true,
    },
  ],

  identityProofFields: [
    {
      name: "proof_of_identity",
      title: "Proof of Identity",
      label: "Proof of Identity",
      type: "file",
      description:
        "Government-issued photo ID such as Passport, Driver's License, Aadhar card, or any other valid ID.",
      style: {},
      inputOptionClassName: "",
      required: true,
    },
  ],
};

module.exports = personalLoanFormFields;
